// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.DDR;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Relay;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.RobotDrive.MotorType;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController subsystem1SpeedController1;
    public static SpeedController subsystem1SpeedController2;
    public static RobotDrive subsystem1RobotDrive21;
    public static DoubleSolenoid shooterSubsystemFillValve;
    public static Relay shooterSubsystemTank1Shoot;
    public static AnalogInput shooterSubsystemPressureSensor;
    public static DoubleSolenoid shooterSubsystemTank1Lid;
    public static AnalogInput shooterSubsystema0;
    public static DoubleSolenoid shooterSubsystemDirectionValve;
    public static Relay shooterSubsystemTank2Shoot;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        subsystem1SpeedController1 = new Talon(0);
        LiveWindow.addActuator("Subsystem 1", "Speed Controller 1", (Talon) subsystem1SpeedController1);
        
        subsystem1SpeedController2 = new Talon(1);
        LiveWindow.addActuator("Subsystem 1", "Speed Controller 2", (Talon) subsystem1SpeedController2);
        
        subsystem1RobotDrive21 = new RobotDrive(subsystem1SpeedController1, subsystem1SpeedController2);
        
        shooterSubsystemFillValve = new DoubleSolenoid(0, 0, 1);      
        LiveWindow.addActuator("ShooterSubsystem", "Fill Valve", shooterSubsystemFillValve);
        
        shooterSubsystemTank1Shoot = new Relay(0);
        LiveWindow.addActuator("ShooterSubsystem", "Tank1Shoot", shooterSubsystemTank1Shoot);
        
        shooterSubsystemPressureSensor = new AnalogInput(1);
        LiveWindow.addSensor("ShooterSubsystem", "Pressure Sensor", shooterSubsystemPressureSensor);
        
        shooterSubsystemTank1Lid = new DoubleSolenoid(0, 2, 3);      
        LiveWindow.addActuator("ShooterSubsystem", "Tank1Lid", shooterSubsystemTank1Lid);
        
        shooterSubsystema0 = new AnalogInput(0);
        LiveWindow.addSensor("ShooterSubsystem", "a0", shooterSubsystema0);
        
        shooterSubsystemDirectionValve = new DoubleSolenoid(0, 4, 5);      
        LiveWindow.addActuator("ShooterSubsystem", "Direction Valve", shooterSubsystemDirectionValve);
        
        shooterSubsystemTank2Shoot = new Relay(1);
        LiveWindow.addActuator("ShooterSubsystem", "Tank2Shoot", shooterSubsystemTank2Shoot);
        
        subsystem1RobotDrive21.setSafetyEnabled(true);
        subsystem1RobotDrive21.setExpiration(0.1);
        subsystem1RobotDrive21.setSensitivity(0.5);
        subsystem1RobotDrive21.setMaxOutput(1.0);

        subsystem1RobotDrive21.setInvertedMotor(MotorType.kRearLeft, true);
        subsystem1RobotDrive21.setInvertedMotor(MotorType.kRearRight, true);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
